name: VividAI-Simplified
options:
  minimumXcodeGenVersion: 2.37.0
  deploymentTarget:
    iOS: '16.0'
  createIntermediateGroups: true
  groupSortPosition: top
  generateEmptyDirectories: true

# Configuration Files
configs:
  Debug: debug
  Release: release
configFiles:
  Debug: Configurations/Debug.xcconfig
  Release: Configurations/Release.xcconfig

packages: {}

targets:
  VividAI:
    type: application
    platform: iOS
    deploymentTarget: '16.0'
    sources:
      - path: .
        excludes:
          - "build/**"
          - "**/*.app"
          - "**/.git"
          - "**/xcodegen.zip"
          - "VividAI.xcodeproj/**"
          - "**/*.ipa"
          - "**/*.xcarchive"
          - ".github/**"
          - "*.md"
          - "*.yml"
          - "*.sh"
          - "**/*.md"
          - "**/*.sh"
          - "**/*.wat"
          - "Scripts/**"
          - "Configurations/**"
          - "Tests/**"
          - "LaunchScreen.storyboard"
    resources:
      - path: Assets.xcassets
      - path: LaunchScreen.storyboard
    dependencies:
      - sdk: Foundation.framework
      - sdk: SwiftUI.framework
      - sdk: UIKit.framework
      - sdk: Combine.framework
      - sdk: CoreData.framework
      - sdk: Vision.framework
      - sdk: AVFoundation.framework
      - sdk: PhotosUI.framework
      - sdk: StoreKit.framework
      - sdk: CoreGraphics.framework
      - sdk: CoreImage.framework
      - sdk: CoreHaptics.framework
      - sdk: AudioToolbox.framework
      - sdk: UserNotifications.framework
      - sdk: AuthenticationServices.framework
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.vividai.app
        PRODUCT_NAME: VividAI
        SWIFT_VERSION: 5.9
        TARGETED_DEVICE_FAMILY: "1,2"
        IPHONEOS_DEPLOYMENT_TARGET: 16.0
        INFOPLIST_FILE: Info.plist
        CODE_SIGNING_ALLOWED: YES
        ALWAYS_SEARCH_USER_PATHS: NO
        CLANG_ENABLE_OBJC_ARC: YES
        CLANG_WARN_BLOCK_CAPTURE_AUTORELEASING: YES
        CLANG_WARN_BOOL_CONVERSION: YES
        CLANG_WARN_COMMA: YES
        CLANG_WARN_CONSTANT_CONVERSION: YES
        CLANG_WARN_DEPRECATED_OBJC_IMPLEMENTATIONS: YES
        CLANG_WARN_DIRECT_OBJC_ISA_USAGE: YES_ERROR
        CLANG_WARN_DOCUMENTATION_COMMENTS: YES
        CLANG_WARN_EMPTY_BODY: YES
        CLANG_WARN_ENUM_CONVERSION: YES
        CLANG_WARN_INFINITE_RECURSION: YES
        CLANG_WARN_INT_CONVERSION: YES
        CLANG_WARN_NON_LITERAL_NULL_CONVERSION: YES
        CLANG_WARN_OBJC_IMPLICIT_RETAIN_SELF: YES
        CLANG_WARN_OBJC_LITERAL_CONVERSION: YES
        CLANG_WARN_OBJC_ROOT_CLASS: YES_ERROR
        CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER: YES
        CLANG_WARN_RANGE_LOOP_ANALYSIS: YES
        CLANG_WARN_STRICT_PROTOTYPES: YES
        CLANG_WARN_SUSPICIOUS_MOVE: YES
        CLANG_WARN_UNGUARDED_AVAILABILITY: YES_AGGRESSIVE
        CLANG_WARN_UNREACHABLE_CODE: YES
        CLANG_WARN__DUPLICATE_METHOD_MATCH: YES
        GCC_C_LANGUAGE_STANDARD: gnu11
        GCC_NO_COMMON_BLOCKS: YES
        GCC_WARN_64_TO_32_BIT_CONVERSION: YES
        GCC_WARN_ABOUT_RETURN_TYPE: YES_ERROR
        GCC_WARN_UNDECLARED_SELECTOR: YES
        GCC_WARN_UNINITIALIZED_AUTOS: YES_AGGRESSIVE
        GCC_WARN_UNUSED_FUNCTION: YES
        GCC_WARN_UNUSED_VARIABLE: YES
        MTL_ENABLE_DEBUG_INFO: INCLUDE_SOURCE
        MTL_FAST_MATH: YES
        SWIFT_EMIT_LOC_STRINGS: YES
        SWIFT_STRICT_CONCURRENCY: targeted
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        ENABLE_USER_SCRIPT_SANDBOXING: YES
        UIRequiresFullScreen: YES
        UIStatusBarStyle: UIStatusBarStyleDefault
        UIViewControllerBasedStatusBarAppearance: NO
        UILaunchStoryboardName: LaunchScreen
      debug:
        SWIFT_OPTIMIZATION_LEVEL: -Onone
        ENABLE_TESTABILITY: YES
        GCC_OPTIMIZATION_LEVEL: 0
        ONLY_ACTIVE_ARCH: YES
        CODE_SIGN_ENTITLEMENTS: VividAI.entitlements
      release:
        SWIFT_OPTIMIZATION_LEVEL: -O
        ENABLE_TESTABILITY: NO
        GCC_OPTIMIZATION_LEVEL: s
        ONLY_ACTIVE_ARCH: NO
        VALIDATE_PRODUCT: YES
        CODE_SIGN_ENTITLEMENTS: VividAI.entitlements
    info:
      path: Info.plist

schemes:
  VividAI:
    build:
      targets:
        VividAI: all
    run:
      config: Debug
    test:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
