# VividAI Podfile
# This file contains the dependencies for the VividAI iOS app

platform :ios, '16.0'
use_frameworks!

target 'VividAI' do
  # Firebase Dependencies
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Analytics'
  pod 'Firebase/Storage'
  
  # Google Sign-In
  pod 'GoogleSignIn'
  
  # Additional Dependencies
  pod 'KeychainAccess'
  pod 'CryptoSwift'
  
  target 'VividAITests' do
    inherit! :search_paths
  end
  
  target 'VividAIUITests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '16.0'
    end
  end
end
