name: VividAI Build Only (No Tests)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Xcode
      run: sudo xcode-select -switch /Applications/Xcode.app/Contents/Developer
      
    - name: List available simulators
      run: xcrun simctl list devices available
      
    - name: Clean derived data
      run: |
        rm -rf ~/Library/Developer/Xcode/DerivedData/*
        
    - name: Build VividAI app (no tests)
      run: |
        xcodebuild clean build \
          -project VividAI.xcodeproj \
          -scheme VividAI \
          -destination 'platform=iOS Simulator,name=iPhone 16,OS=18.4' \
          -configuration Debug \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO \
          -skipPackagePluginValidation
          
    - name: Verify build success
      run: |
        echo "✅ Build completed successfully!"
        ls -la /Users/runner/Library/Developer/Xcode/DerivedData/*/Build/Products/Debug-iphonesimulator/
