name: Test Firebase Dependencies

on:
  workflow_dispatch:  # Manual trigger

jobs:
  test-firebase-deps:
    runs-on: macos-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Xcode
      run: sudo xcode-select -switch /Applications/Xcode.app/Contents/Developer
      
    - name: Test Firebase package resolution
      run: |
        echo "🔍 Testing Firebase package resolution..."
        
        # Try to resolve dependencies and see what products are available
        xcodebuild -resolvePackageDependencies -project VividAI.xcodeproj -verbose
        
        echo "✅ Package resolution completed"
        
    - name: List available Firebase products
      run: |
        echo "📦 Checking what Firebase products are available..."
        
        # Try to build with verbose output to see what products are found
        xcodebuild build \
          -project VividAI.xcodeproj \
          -scheme VividAI \
          -destination 'platform=iOS Simulator,name=iPhone 16,OS=18.4' \
          -configuration Debug \
          -verbose \
          -derivedDataPath ./DerivedData \
          || echo "Build failed as expected, but we can see the available products"
